import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, SignIn, UserButton, useAuth } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useAuth();



  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="navbar bg-base-300">
          <div className="navbar-start">
            <span>Chirp</span>
          </div>
          <div className="navbar-end flex gap-2">
            {!user.isSignedIn && <SignInButton className="btn btn-primary"></SignInButton> }
            <UserButton></UserButton>
          </div>
        </div>

        


      </main>
    </>
  );
};

export default Home;
